
CREATE DATABASE IF NOT EXISTS School;
USE school;
CREATE  IF NOT EXISTS Students 
( sid INT PRIMARY, sname VARCHAR(30), gender CHAR(1), mark DECIMAL(4,2)) ;
INSERT INTO students VALUES (101,"Neha","F",97);
INSERT INTO students VALUES (111,"Ria","F",67);
INSERT INTO students VALUES (231,"Mohan","M",78);
INSERT INTO students VALUES (124,"Rohan","M",94);
INSERT INTO students VALUES (121,"Misha","F",92);
(Query I)
ALTER TABLE students
ADD city varchar(15)
ADD phone varchar(10);
(QUERY II)
ALTER TABLE STUDENTS
MODIFY city VARCHAR(20);
(QUERY III)
ALTER TABLE STUDENTS
DROP COLUMN city;
(QUERY IV)
UPDATE STUDENTS
SET mark = 75
WHERE sname = "Ria";
(QUERY V)
SELECT sname,mark from students
ORDER BY mark;
(QUERY VI)
SELECT * FROM STUDENTS
ORDER BY sid DESC;
(QUERY VII)
SELECT GENDER, COUNT(GENDER) FROM STUDENTS
GROUP BY GENDER;
(QUERY VIII)
SELECT GENDER, MIN(MARK) , MAX(MARK), SUM(MARK), AVG(MARK) FROM STUDENTS
GROUP BY GENDER;
(QUERY IX)
DELETE FROM STUDENTS WHERE sid = 231;
(QUERY X)
SELECT GENDER, MAX(MARK) FROM STUDENTS
GROUP BY GENDER;